### ISSUE TITLE
security vulnerability found

### ISSUE THREAD

**Issue by porcupineyhairs** [mohammed90/caddy-ssh#16]
Hi,

I would like to report a security vulnerability in this project. Can you please create a [security advisory](https://docs.github.com/en/code-security/repository-security-advisories/creating-a-repository-security-advisory) and add me as a collaborator?

**Comment by mohammed90** [comment]
Done.

**Comment by mohammed90** [comment]
Fixed in 4b3e639d64c55f91152ffb51a4af35a8845c95a3 and published in https://github.com/mohammed90/caddy-ssh/security/advisories/GHSA-gmhj-xjfh-cf6m
